# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

POST http://127.0.0.1:8000/analyze
Content-Type: application/json
Accept: application/json

{
  "text": "прееска бев излезен и падна гранка од дрво на мене. мислам дека ми е скршена раката и ме боли"
}
###
